export const ARTICLE_FETCH_REQUEST = 'ARTICLE_FETCH_REQUEST';
export const ARTICLE_FETCH_SUCCEEDED = 'ARTICLE_FETCH_SUCCEEDED';
export const ARTICLE_FETCH_FAILED = 'ARTICLE_FETCH_FAILED';
export const GET_START_ARTICLES = 'GET_START_ARTICLES';